<map id="pip._vendor.urllib3.exceptions.NewConnectionError" name="pip._vendor.urllib3.exceptions.NewConnectionError">
<area shape="rect" id="node2" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1ConnectTimeoutError.html" title="pip._vendor.urllib3.exceptions.\lConnectTimeoutError" alt="" coords="627,5,825,47"/>
<area shape="rect" id="node3" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1TimeoutError.html" title="pip._vendor.urllib3.exceptions.\lTimeoutError" alt="" coords="380,8,579,49"/>
<area shape="rect" id="node4" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1HTTPError.html" title="pip._vendor.urllib3.exceptions.\lHTTPError" alt="" coords="133,39,332,80"/>
<area shape="rect" id="node6" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1PoolError.html" title="pip._vendor.urllib3.exceptions.\lPoolError" alt="" coords="627,71,825,112"/>
</map>
