\hypertarget{classpip_1_1__internal_1_1exceptions_1_1PipError}{}\section{pip.\+\_\+internal.\+exceptions.\+Pip\+Error Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1PipError}\index{pip.\+\_\+internal.\+exceptions.\+Pip\+Error@{pip.\+\_\+internal.\+exceptions.\+Pip\+Error}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Pip\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classpip_1_1__internal_1_1exceptions_1_1PipError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Pip\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=202pt]{classpip_1_1__internal_1_1exceptions_1_1PipError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Base pip exception\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/pip/\+\_\+internal/\hyperlink{pip_2__internal_2exceptions_8py}{exceptions.\+py}\end{DoxyCompactItemize}
