\hypertarget{classnetworkx_1_1exception_1_1NetworkXError}{}\section{networkx.\+exception.\+Network\+X\+Error Class Reference}
\label{classnetworkx_1_1exception_1_1NetworkXError}\index{networkx.\+exception.\+Network\+X\+Error@{networkx.\+exception.\+Network\+X\+Error}}


Inheritance diagram for networkx.\+exception.\+Network\+X\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=270pt]{classnetworkx_1_1exception_1_1NetworkXError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for networkx.\+exception.\+Network\+X\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=221pt]{classnetworkx_1_1exception_1_1NetworkXError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Exception for a serious error in NetworkX\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/networkx/\hyperlink{exception_8py}{exception.\+py}\end{DoxyCompactItemize}
