\hypertarget{classnetworkx_1_1exception_1_1NetworkXUnbounded}{}\section{networkx.\+exception.\+Network\+X\+Unbounded Class Reference}
\label{classnetworkx_1_1exception_1_1NetworkXUnbounded}\index{networkx.\+exception.\+Network\+X\+Unbounded@{networkx.\+exception.\+Network\+X\+Unbounded}}


Inheritance diagram for networkx.\+exception.\+Network\+X\+Unbounded\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=221pt]{classnetworkx_1_1exception_1_1NetworkXUnbounded__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for networkx.\+exception.\+Network\+X\+Unbounded\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=221pt]{classnetworkx_1_1exception_1_1NetworkXUnbounded__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Exception raised by algorithms trying to solve a maximization
or a minimization problem instance that is unbounded.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/networkx/\hyperlink{exception_8py}{exception.\+py}\end{DoxyCompactItemize}
