\hypertarget{classpytz_1_1exceptions_1_1InvalidTimeError}{}\section{pytz.\+exceptions.\+Invalid\+Time\+Error Class Reference}
\label{classpytz_1_1exceptions_1_1InvalidTimeError}\index{pytz.\+exceptions.\+Invalid\+Time\+Error@{pytz.\+exceptions.\+Invalid\+Time\+Error}}


Inheritance diagram for pytz.\+exceptions.\+Invalid\+Time\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classpytz_1_1exceptions_1_1InvalidTimeError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pytz.\+exceptions.\+Invalid\+Time\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=219pt]{classpytz_1_1exceptions_1_1InvalidTimeError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Base class for invalid time exceptions.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/pytz/\hyperlink{pytz_2exceptions_8py}{exceptions.\+py}\end{DoxyCompactItemize}
