\hypertarget{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1TimeoutError}{}\section{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error Class Reference}
\label{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1TimeoutError}\index{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error@{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error}}


Inheritance diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1TimeoutError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Timeout\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=229pt]{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1TimeoutError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Raised when a socket timeout error occurs.

Catching this error will catch both :exc:`ReadTimeoutErrors
<ReadTimeoutError>` and :exc:`ConnectTimeoutErrors <ConnectTimeoutError>`.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/pip/\+\_\+vendor/urllib3/\hyperlink{pip_2__vendor_2urllib3_2exceptions_8py}{exceptions.\+py}\end{DoxyCompactItemize}
